'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Negocios2014")>  _
Partial Public Class dNegociosDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Insertempleados(instance As empleados)
    End Sub
  Partial Private Sub Updateempleados(instance As empleados)
    End Sub
  Partial Private Sub Deleteempleados(instance As empleados)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Semana13b.My.MySettings.Default.Negocios2014ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property empleados() As System.Data.Linq.Table(Of empleados)
		Get
			Return Me.GetTable(Of empleados)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_CLIENTESXPAIS")>  _
	Public Function SP_CLIENTESXPAIS(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="PAIS", DbType:="Char(3)")> ByVal pAIS As String) As ISingleResult(Of SP_CLIENTESXPAISResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), pAIS)
		Return CType(result.ReturnValue,ISingleResult(Of SP_CLIENTESXPAISResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTACARGOS")>  _
	Public Function SP_LISTACARGOS() As ISingleResult(Of SP_LISTACARGOSResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTACARGOSResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTACATEGORIAS")>  _
	Public Function SP_LISTACATEGORIAS() As ISingleResult(Of SP_LISTACATEGORIASResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTACATEGORIASResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTACLIENTES")>  _
	Public Function SP_LISTACLIENTES() As ISingleResult(Of SP_LISTACLIENTESResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTACLIENTESResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTADISTRITOS")>  _
	Public Function SP_LISTADISTRITOS() As ISingleResult(Of SP_LISTADISTRITOSResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTADISTRITOSResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTAPAIS")>  _
	Public Function SP_LISTAPAIS() As ISingleResult(Of SP_LISTAPAISResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTAPAISResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTAPRODUCTOS")>  _
	Public Function SP_LISTAPRODUCTOS() As ISingleResult(Of SP_LISTAPRODUCTOSResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTAPRODUCTOSResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTAPROVEEDORES")>  _
	Public Function SP_LISTAPROVEEDORES() As ISingleResult(Of SP_LISTAPROVEEDORESResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTAPROVEEDORESResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_ULTIMOEMPLEADO")>  _
	Public Function SP_ULTIMOEMPLEADO() As ISingleResult(Of SP_ULTIMOEMPLEADOResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_ULTIMOEMPLEADOResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_ULTIMOPRODUCTO")>  _
	Public Function SP_ULTIMOPRODUCTO() As ISingleResult(Of SP_ULTIMOPRODUCTOResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_ULTIMOPRODUCTOResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_LISTAEMPELADOS")>  _
	Public Function SP_LISTAEMPELADOS() As ISingleResult(Of SP_LISTAEMPELADOSResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of SP_LISTAEMPELADOSResult))
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="RRHH.empleados")>  _
Partial Public Class empleados
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdEmpleado As Integer
	
	Private _ApeEmpleado As String
	
	Private _NomEmpleado As String
	
	Private _FecNac As Date
	
	Private _DirEmpleado As String
	
	Private _idDistrito As System.Nullable(Of Integer)
	
	Private _fonoEmpleado As String
	
	Private _idCargo As System.Nullable(Of Integer)
	
	Private _FecContrata As Date
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdEmpleadoChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdEmpleadoChanged()
    End Sub
    Partial Private Sub OnApeEmpleadoChanging(value As String)
    End Sub
    Partial Private Sub OnApeEmpleadoChanged()
    End Sub
    Partial Private Sub OnNomEmpleadoChanging(value As String)
    End Sub
    Partial Private Sub OnNomEmpleadoChanged()
    End Sub
    Partial Private Sub OnFecNacChanging(value As Date)
    End Sub
    Partial Private Sub OnFecNacChanged()
    End Sub
    Partial Private Sub OnDirEmpleadoChanging(value As String)
    End Sub
    Partial Private Sub OnDirEmpleadoChanged()
    End Sub
    Partial Private Sub OnidDistritoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnidDistritoChanged()
    End Sub
    Partial Private Sub OnfonoEmpleadoChanging(value As String)
    End Sub
    Partial Private Sub OnfonoEmpleadoChanged()
    End Sub
    Partial Private Sub OnidCargoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnidCargoChanged()
    End Sub
    Partial Private Sub OnFecContrataChanging(value As Date)
    End Sub
    Partial Private Sub OnFecContrataChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdEmpleado", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property IdEmpleado() As Integer
		Get
			Return Me._IdEmpleado
		End Get
		Set
			If ((Me._IdEmpleado = value)  _
						= false) Then
				Me.OnIdEmpleadoChanging(value)
				Me.SendPropertyChanging
				Me._IdEmpleado = value
				Me.SendPropertyChanged("IdEmpleado")
				Me.OnIdEmpleadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ApeEmpleado", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ApeEmpleado() As String
		Get
			Return Me._ApeEmpleado
		End Get
		Set
			If (String.Equals(Me._ApeEmpleado, value) = false) Then
				Me.OnApeEmpleadoChanging(value)
				Me.SendPropertyChanging
				Me._ApeEmpleado = value
				Me.SendPropertyChanged("ApeEmpleado")
				Me.OnApeEmpleadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomEmpleado", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NomEmpleado() As String
		Get
			Return Me._NomEmpleado
		End Get
		Set
			If (String.Equals(Me._NomEmpleado, value) = false) Then
				Me.OnNomEmpleadoChanging(value)
				Me.SendPropertyChanging
				Me._NomEmpleado = value
				Me.SendPropertyChanged("NomEmpleado")
				Me.OnNomEmpleadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FecNac", DbType:="DateTime NOT NULL")>  _
	Public Property FecNac() As Date
		Get
			Return Me._FecNac
		End Get
		Set
			If ((Me._FecNac = value)  _
						= false) Then
				Me.OnFecNacChanging(value)
				Me.SendPropertyChanging
				Me._FecNac = value
				Me.SendPropertyChanged("FecNac")
				Me.OnFecNacChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DirEmpleado", DbType:="VarChar(60) NOT NULL", CanBeNull:=false)>  _
	Public Property DirEmpleado() As String
		Get
			Return Me._DirEmpleado
		End Get
		Set
			If (String.Equals(Me._DirEmpleado, value) = false) Then
				Me.OnDirEmpleadoChanging(value)
				Me.SendPropertyChanging
				Me._DirEmpleado = value
				Me.SendPropertyChanged("DirEmpleado")
				Me.OnDirEmpleadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idDistrito", DbType:="Int")>  _
	Public Property idDistrito() As System.Nullable(Of Integer)
		Get
			Return Me._idDistrito
		End Get
		Set
			If (Me._idDistrito.Equals(value) = false) Then
				Me.OnidDistritoChanging(value)
				Me.SendPropertyChanging
				Me._idDistrito = value
				Me.SendPropertyChanged("idDistrito")
				Me.OnidDistritoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fonoEmpleado", DbType:="VarChar(15)")>  _
	Public Property fonoEmpleado() As String
		Get
			Return Me._fonoEmpleado
		End Get
		Set
			If (String.Equals(Me._fonoEmpleado, value) = false) Then
				Me.OnfonoEmpleadoChanging(value)
				Me.SendPropertyChanging
				Me._fonoEmpleado = value
				Me.SendPropertyChanged("fonoEmpleado")
				Me.OnfonoEmpleadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idCargo", DbType:="Int")>  _
	Public Property idCargo() As System.Nullable(Of Integer)
		Get
			Return Me._idCargo
		End Get
		Set
			If (Me._idCargo.Equals(value) = false) Then
				Me.OnidCargoChanging(value)
				Me.SendPropertyChanging
				Me._idCargo = value
				Me.SendPropertyChanged("idCargo")
				Me.OnidCargoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FecContrata", DbType:="DateTime NOT NULL")>  _
	Public Property FecContrata() As Date
		Get
			Return Me._FecContrata
		End Get
		Set
			If ((Me._FecContrata = value)  _
						= false) Then
				Me.OnFecContrataChanging(value)
				Me.SendPropertyChanging
				Me._FecContrata = value
				Me.SendPropertyChanged("FecContrata")
				Me.OnFecContrataChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

Partial Public Class SP_CLIENTESXPAISResult
	
	Private _IdCliente As String
	
	Private _NomCliente As String
	
	Private _DirCliente As String
	
	Private _idpais As String
	
	Private _fonoCliente As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCliente", DbType:="VarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property IdCliente() As String
		Get
			Return Me._IdCliente
		End Get
		Set
			If (String.Equals(Me._IdCliente, value) = false) Then
				Me._IdCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomCliente", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property NomCliente() As String
		Get
			Return Me._NomCliente
		End Get
		Set
			If (String.Equals(Me._NomCliente, value) = false) Then
				Me._NomCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DirCliente", DbType:="VarChar(60) NOT NULL", CanBeNull:=false)>  _
	Public Property DirCliente() As String
		Get
			Return Me._DirCliente
		End Get
		Set
			If (String.Equals(Me._DirCliente, value) = false) Then
				Me._DirCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idpais", DbType:="Char(3)")>  _
	Public Property idpais() As String
		Get
			Return Me._idpais
		End Get
		Set
			If (String.Equals(Me._idpais, value) = false) Then
				Me._idpais = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fonoCliente", DbType:="VarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property fonoCliente() As String
		Get
			Return Me._fonoCliente
		End Get
		Set
			If (String.Equals(Me._fonoCliente, value) = false) Then
				Me._fonoCliente = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTACARGOSResult
	
	Private _idcargo As Integer
	
	Private _desCargo As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idcargo", DbType:="Int NOT NULL")>  _
	Public Property idcargo() As Integer
		Get
			Return Me._idcargo
		End Get
		Set
			If ((Me._idcargo = value)  _
						= false) Then
				Me._idcargo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_desCargo", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property desCargo() As String
		Get
			Return Me._desCargo
		End Get
		Set
			If (String.Equals(Me._desCargo, value) = false) Then
				Me._desCargo = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTACATEGORIASResult
	
	Private _IdCategoria As Integer
	
	Private _NombreCategoria As String
	
	Private _Descripcion As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCategoria", DbType:="Int NOT NULL")>  _
	Public Property IdCategoria() As Integer
		Get
			Return Me._IdCategoria
		End Get
		Set
			If ((Me._IdCategoria = value)  _
						= false) Then
				Me._IdCategoria = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NombreCategoria", DbType:="VarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property NombreCategoria() As String
		Get
			Return Me._NombreCategoria
		End Get
		Set
			If (String.Equals(Me._NombreCategoria, value) = false) Then
				Me._NombreCategoria = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Descripcion", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Descripcion() As String
		Get
			Return Me._Descripcion
		End Get
		Set
			If (String.Equals(Me._Descripcion, value) = false) Then
				Me._Descripcion = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTACLIENTESResult
	
	Private _IdCliente As String
	
	Private _NomCliente As String
	
	Private _DirCliente As String
	
	Private _idpais As String
	
	Private _fonoCliente As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCliente", DbType:="VarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property IdCliente() As String
		Get
			Return Me._IdCliente
		End Get
		Set
			If (String.Equals(Me._IdCliente, value) = false) Then
				Me._IdCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomCliente", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property NomCliente() As String
		Get
			Return Me._NomCliente
		End Get
		Set
			If (String.Equals(Me._NomCliente, value) = false) Then
				Me._NomCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DirCliente", DbType:="VarChar(60) NOT NULL", CanBeNull:=false)>  _
	Public Property DirCliente() As String
		Get
			Return Me._DirCliente
		End Get
		Set
			If (String.Equals(Me._DirCliente, value) = false) Then
				Me._DirCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idpais", DbType:="Char(3)")>  _
	Public Property idpais() As String
		Get
			Return Me._idpais
		End Get
		Set
			If (String.Equals(Me._idpais, value) = false) Then
				Me._idpais = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fonoCliente", DbType:="VarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property fonoCliente() As String
		Get
			Return Me._fonoCliente
		End Get
		Set
			If (String.Equals(Me._fonoCliente, value) = false) Then
				Me._fonoCliente = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTADISTRITOSResult
	
	Private _idDistrito As Integer
	
	Private _nomDistrito As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idDistrito", DbType:="Int NOT NULL")>  _
	Public Property idDistrito() As Integer
		Get
			Return Me._idDistrito
		End Get
		Set
			If ((Me._idDistrito = value)  _
						= false) Then
				Me._idDistrito = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nomDistrito", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property nomDistrito() As String
		Get
			Return Me._nomDistrito
		End Get
		Set
			If (String.Equals(Me._nomDistrito, value) = false) Then
				Me._nomDistrito = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTAPAISResult
	
	Private _Idpais As String
	
	Private _NombrePais As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Idpais", DbType:="Char(3) NOT NULL", CanBeNull:=false)>  _
	Public Property Idpais() As String
		Get
			Return Me._Idpais
		End Get
		Set
			If (String.Equals(Me._Idpais, value) = false) Then
				Me._Idpais = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NombrePais", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property NombrePais() As String
		Get
			Return Me._NombrePais
		End Get
		Set
			If (String.Equals(Me._NombrePais, value) = false) Then
				Me._NombrePais = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTAPRODUCTOSResult
	
	Private _IdProducto As Integer
	
	Private _NomProducto As String
	
	Private _IdProveedor As System.Nullable(Of Integer)
	
	Private _IdCategoria As System.Nullable(Of Integer)
	
	Private _CantxUnidad As String
	
	Private _PrecioUnidad As Decimal
	
	Private _UnidadesEnExistencia As Short
	
	Private _UnidadesEnPedido As Short
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProducto", DbType:="Int NOT NULL")>  _
	Public Property IdProducto() As Integer
		Get
			Return Me._IdProducto
		End Get
		Set
			If ((Me._IdProducto = value)  _
						= false) Then
				Me._IdProducto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomProducto", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property NomProducto() As String
		Get
			Return Me._NomProducto
		End Get
		Set
			If (String.Equals(Me._NomProducto, value) = false) Then
				Me._NomProducto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProveedor", DbType:="Int")>  _
	Public Property IdProveedor() As System.Nullable(Of Integer)
		Get
			Return Me._IdProveedor
		End Get
		Set
			If (Me._IdProveedor.Equals(value) = false) Then
				Me._IdProveedor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCategoria", DbType:="Int")>  _
	Public Property IdCategoria() As System.Nullable(Of Integer)
		Get
			Return Me._IdCategoria
		End Get
		Set
			If (Me._IdCategoria.Equals(value) = false) Then
				Me._IdCategoria = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CantxUnidad", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property CantxUnidad() As String
		Get
			Return Me._CantxUnidad
		End Get
		Set
			If (String.Equals(Me._CantxUnidad, value) = false) Then
				Me._CantxUnidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PrecioUnidad", DbType:="Decimal(10,0) NOT NULL")>  _
	Public Property PrecioUnidad() As Decimal
		Get
			Return Me._PrecioUnidad
		End Get
		Set
			If ((Me._PrecioUnidad = value)  _
						= false) Then
				Me._PrecioUnidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UnidadesEnExistencia", DbType:="SmallInt NOT NULL")>  _
	Public Property UnidadesEnExistencia() As Short
		Get
			Return Me._UnidadesEnExistencia
		End Get
		Set
			If ((Me._UnidadesEnExistencia = value)  _
						= false) Then
				Me._UnidadesEnExistencia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UnidadesEnPedido", DbType:="SmallInt NOT NULL")>  _
	Public Property UnidadesEnPedido() As Short
		Get
			Return Me._UnidadesEnPedido
		End Get
		Set
			If ((Me._UnidadesEnPedido = value)  _
						= false) Then
				Me._UnidadesEnPedido = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTAPROVEEDORESResult
	
	Private _IdProveedor As Integer
	
	Private _NomProveedor As String
	
	Private _DirProveedor As String
	
	Private _NomContacto As String
	
	Private _CargoContacto As String
	
	Private _idpais As String
	
	Private _fonoProveedor As String
	
	Private _FaxProveedor As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProveedor", DbType:="Int NOT NULL")>  _
	Public Property IdProveedor() As Integer
		Get
			Return Me._IdProveedor
		End Get
		Set
			If ((Me._IdProveedor = value)  _
						= false) Then
				Me._IdProveedor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomProveedor", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property NomProveedor() As String
		Get
			Return Me._NomProveedor
		End Get
		Set
			If (String.Equals(Me._NomProveedor, value) = false) Then
				Me._NomProveedor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DirProveedor", DbType:="VarChar(60) NOT NULL", CanBeNull:=false)>  _
	Public Property DirProveedor() As String
		Get
			Return Me._DirProveedor
		End Get
		Set
			If (String.Equals(Me._DirProveedor, value) = false) Then
				Me._DirProveedor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomContacto", DbType:="VarChar(80) NOT NULL", CanBeNull:=false)>  _
	Public Property NomContacto() As String
		Get
			Return Me._NomContacto
		End Get
		Set
			If (String.Equals(Me._NomContacto, value) = false) Then
				Me._NomContacto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CargoContacto", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property CargoContacto() As String
		Get
			Return Me._CargoContacto
		End Get
		Set
			If (String.Equals(Me._CargoContacto, value) = false) Then
				Me._CargoContacto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idpais", DbType:="Char(3)")>  _
	Public Property idpais() As String
		Get
			Return Me._idpais
		End Get
		Set
			If (String.Equals(Me._idpais, value) = false) Then
				Me._idpais = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fonoProveedor", DbType:="VarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property fonoProveedor() As String
		Get
			Return Me._fonoProveedor
		End Get
		Set
			If (String.Equals(Me._fonoProveedor, value) = false) Then
				Me._fonoProveedor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FaxProveedor", DbType:="VarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property FaxProveedor() As String
		Get
			Return Me._FaxProveedor
		End Get
		Set
			If (String.Equals(Me._FaxProveedor, value) = false) Then
				Me._FaxProveedor = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_ULTIMOEMPLEADOResult
	
	Private _IdEmpleado As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdEmpleado", DbType:="Int NOT NULL")>  _
	Public Property IdEmpleado() As Integer
		Get
			Return Me._IdEmpleado
		End Get
		Set
			If ((Me._IdEmpleado = value)  _
						= false) Then
				Me._IdEmpleado = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_ULTIMOPRODUCTOResult
	
	Private _IdProducto As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProducto", DbType:="Int NOT NULL")>  _
	Public Property IdProducto() As Integer
		Get
			Return Me._IdProducto
		End Get
		Set
			If ((Me._IdProducto = value)  _
						= false) Then
				Me._IdProducto = value
			End If
		End Set
	End Property
End Class

Partial Public Class SP_LISTAEMPELADOSResult
	
	Private _IdEmpleado As Integer
	
	Private _ApeEmpleado As String
	
	Private _NomEmpleado As String
	
	Private _FecNac As Date
	
	Private _DirEmpleado As String
	
	Private _idDistrito As System.Nullable(Of Integer)
	
	Private _idCargo As System.Nullable(Of Integer)
	
	Private _FecContrata As Date
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdEmpleado", DbType:="Int NOT NULL")>  _
	Public Property IdEmpleado() As Integer
		Get
			Return Me._IdEmpleado
		End Get
		Set
			If ((Me._IdEmpleado = value)  _
						= false) Then
				Me._IdEmpleado = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ApeEmpleado", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ApeEmpleado() As String
		Get
			Return Me._ApeEmpleado
		End Get
		Set
			If (String.Equals(Me._ApeEmpleado, value) = false) Then
				Me._ApeEmpleado = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomEmpleado", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NomEmpleado() As String
		Get
			Return Me._NomEmpleado
		End Get
		Set
			If (String.Equals(Me._NomEmpleado, value) = false) Then
				Me._NomEmpleado = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FecNac", DbType:="DateTime NOT NULL")>  _
	Public Property FecNac() As Date
		Get
			Return Me._FecNac
		End Get
		Set
			If ((Me._FecNac = value)  _
						= false) Then
				Me._FecNac = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DirEmpleado", DbType:="VarChar(60) NOT NULL", CanBeNull:=false)>  _
	Public Property DirEmpleado() As String
		Get
			Return Me._DirEmpleado
		End Get
		Set
			If (String.Equals(Me._DirEmpleado, value) = false) Then
				Me._DirEmpleado = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idDistrito", DbType:="Int")>  _
	Public Property idDistrito() As System.Nullable(Of Integer)
		Get
			Return Me._idDistrito
		End Get
		Set
			If (Me._idDistrito.Equals(value) = false) Then
				Me._idDistrito = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idCargo", DbType:="Int")>  _
	Public Property idCargo() As System.Nullable(Of Integer)
		Get
			Return Me._idCargo
		End Get
		Set
			If (Me._idCargo.Equals(value) = false) Then
				Me._idCargo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FecContrata", DbType:="DateTime NOT NULL")>  _
	Public Property FecContrata() As Date
		Get
			Return Me._FecContrata
		End Get
		Set
			If ((Me._FecContrata = value)  _
						= false) Then
				Me._FecContrata = value
			End If
		End Set
	End Property
End Class
