USE VENTAS2014
GO

IF OBJECT_ID('SP_LISTARNOMBRES') IS NOT NULL
	DROP PROC SP_LISTARNOMBRES
GO

CREATE PROC SP_LISTARNOMBRES
AS
BEGIN
	SELECT [COD_CLI], [NOMBRES] FROM [dbo].[CLIENTE]
END
GO
EXEC SP_LISTARNOMBRES
GO


--

IF OBJECT_ID('SP_LISTARBOLETASXNOMBRE') IS NOT NULL
	DROP PROC SP_LISTARBOLETASXNOMBRE
GO

CREATE PROC SP_LISTARBOLETASXNOMBRE
@COD_CLI CHAR(6)
AS
BEGIN
	SELECT * FROM [dbo].[BOLETA] B WHERE [COD_CLI]=@COD_CLI 
END
GO
EXEC SP_LISTARBOLETASXNOMBRE 'CL0001'
GO

