'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clientes
    Public Property IdCliente As String
    Public Property NomCliente As String
    Public Property DirCliente As String
    Public Property idpais As String
    Public Property fonoCliente As String

    Public Overridable Property paises As paises

End Class
