'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class productos
    Public Property IdProducto As Integer
    Public Property NomProducto As String
    Public Property IdProveedor As Nullable(Of Integer)
    Public Property IdCategoria As Nullable(Of Integer)
    Public Property CantxUnidad As String
    Public Property PrecioUnidad As Decimal
    Public Property UnidadesEnExistencia As Short
    Public Property UnidadesEnPedido As Short

End Class
