USE Contratos
GO

IF OBJECT_ID('SP_LISTAINQUILINOS') IS NOT NULL
	DROP PROC SP_LISTAINQUILINOS
GO

CREATE PROC SP_LISTAINQUILINOS
AS
BEGIN
	SELECT COD_USUA AS CODIGO,
		NOM_AVAL_INQ AS NOMBRE,
			APELL_AVAL AS APELLIDO,
			HABER_BAS_INQ AS BASICO,
			EST_CIVIL_INQ AS 'ESTADO CIVIL',
			LUG_TRAB_INQ AS 'LUGAR DE TRABAJO' FROM [dbo].[INQUILINO]
END
GO


IF OBJECT_ID('SP_AUTO') IS NOT NULL
	DROP PROC SP_AUTO
GO

CREATE PROC SP_AUTO
@COD CHAR(6) OUTPUT
AS
BEGIN
	DECLARE @C INTEGER
	SELECT @C= CONVERT(INT, RIGHT(MAX([COD_USUA]),3)) FROM [dbo].[INQUILINO]
	SELECT @COD='USU'+ RIGHT(STR(@C+1001),3)
END
GO

DECLARE @COD CHAR(6) 
EXEC SP_AUTO  @COD OUTPUT
SELECT @COD
GO

IF OBJECT_ID('SP_INSERTARQUILINOS') IS NOT NULL
	DROP PROC SP_INSERTARQUILINOS
GO

CREATE PROC SP_INSERTARQUILINOS
@COD_USUA CHAR(6),
@NOM_AVAL_INQ VARCHAR(30),
@APELL_AVAL CHAR(30),
@HABER_BAS_INQ INT,
@EST_CIVIL_INQ CHAR(1),
@LUG_TRAB_INQ VARCHAR(50)
AS
BEGIN
	INSERT INTO [dbo].[INQUILINO] VALUES(@COD_USUA,
										@NOM_AVAL_INQ,
										@APELL_AVAL,
										@HABER_BAS_INQ,
										@EST_CIVIL_INQ,
										@LUG_TRAB_INQ)
END
GO


IF OBJECT_ID('SP_MODIFICARQUILINOS') IS NOT NULL
	DROP PROC SP_MODIFICARQUILINOS
GO

CREATE PROC SP_MODIFICARQUILINOS
@COD_USUA CHAR(6),
@NOM_AVAL_INQ VARCHAR(30),
@APELL_AVAL CHAR(30),
@HABER_BAS_INQ INT,
@EST_CIVIL_INQ CHAR(1),
@LUG_TRAB_INQ VARCHAR(50)
AS
BEGIN
	UPDATE [dbo].[INQUILINO] SET NOM_AVAL_INQ=@NOM_AVAL_INQ,
										APELL_AVAL=@APELL_AVAL,
										HABER_BAS_INQ=@HABER_BAS_INQ,
										EST_CIVIL_INQ=@EST_CIVIL_INQ,
										LUG_TRAB_INQ=@LUG_TRAB_INQ
	WHERE @COD_USUA=COD_USUA										
END
GO
