USE MASTER
GO

CREATE DATABASE BDFOTOS
GO

USE BDFOTOS
GO

--CREANDO LA TABLA PRODUCTOF PARA EL MANEJO DE IMAGENES
CREATE TABLE PRODUCTOF(
COD_PRO CHAR(4) not null PRIMARY KEY,
DESCRIP_PRO VARCHAR (40) NOT NULL,
PRECIO_PRO MONEY NOT NULL,
STOCK_ACT_PRO INT NOT NULL,
STOCK_MIN_PRO INT NOT NULL,
FOTO IMAGE
)
GO

--INSERTANDO IMÁGENES A LA TABLA PRODUCTOF
INSERT INTO PRODUCTOF
SELECT 'P001','PYE DE MANZANA',20,500,200,
BULKCOLUMN FROM OPENROWSET
(BULK 'C:\FOTOSPRODUCTOS\P001.JPG',SINGLE_BLOB) AS PRO
INSERT INTO PRODUCTOF
SELECT 'P002','TORTA DE CHOCOLATE',45,100,50,
BULKCOLUMN FROM OPENROWSET
(BULK 'C:\FOTOSPRODUCTOS\P002.JPG',SINGLE_BLOB) AS PRO
--CREANDO EL PROCEDIMIENTO ALMACENADO QUE PERMITA REGISTRAR UN NUEVO PRODUCTO
--CON UNA IMAGEN DEL PRODUCTO
IF OBJECT_ID('SP_NUEVOPRODUCTOF') IS NOT NULL
DROP PROC SP_NUEVOPRODUCTOF
GO
CREATE PROC SP_NUEVOPRODUCTOF(@COD CHAR(4),@DESC VARCHAR(50),@PRE MONEY,
@STOCKA INT,@STOCKM INT,@FOTO IMAGE)
AS
INSERT INTO PRODUCTOF VALUES(@COD,@DESC,@PRE,@STOCKA,@STOCKM,@FOTO)
GO

if OBJECT_ID('SP_GENERA') is not null
	drop proc SP_GENERA
go
Create Proc SP_GENERA
@Cod CHAR(4) output
as
Declare @CodAux char(3)
Select @CodAux=Max(Right(rtrim(COD_PRO),3)) 
From PRODUCTOF
Select @Cod='P'+Right(str(Convert(int,@CodAux)+100001),3)
go
--Verificar
Declare @Codigo char(6) 
Exec SP_GENERA @Codigo output 
Select @Codigo

--CREANDO EL PROCEDIMIENTO ALMACENADO QUE PERMITA BUSCAR UN DETERMINADO
--PRODUCTO
IF OBJECT_ID('SP_BUSCAPRODUCTOF') IS NOT NULL
DROP PROC SP_BUSCAPRODUCTOF
GO
CREATE PROC SP_BUSCAPRODUCTOF(@COD CHAR(4))
AS
SELECT * FROM PRODUCTOF
WHERE COD_PRO=@cod
GO