USE PESCA
GO

SET DATEFORMAT dMy
go

IF OBJECT_ID('SP_LISTA_FECHA_INICIO') IS NOT NULL
	DROP PROC SP_LISTA_FECHA_INICIO
GO

CREATE PROC SP_LISTA_FECHA_INICIO
AS
BEGIN
	SELECT [FEC_INI]  FROM [dbo].[TB_FAENA]
END
GO


EXEC SP_LISTA_FECHA_INICIO
GO


---

IF OBJECT_ID('SP_LISTA_BARCOS_FECHA_INICIO') IS NOT NULL
	DROP PROC SP_LISTA_BARCOS_FECHA_INICIO
GO

CREATE PROC SP_LISTA_BARCOS_FECHA_INICIO
@FI1 AS DATETIME,
@FI2 AS DATETIME
AS
BEGIN
	SELECT B.*  FROM [dbo].[TB_BARCO] AS B INNER JOIN [dbo].[TB_FAENA] AS F 
	ON B.COD_BAR=F.COD_BAR WHERE F.FEC_INI BETWEEN @FI1 AND @FI2
END
GO

EXEC SP_LISTA_BARCOS_FECHA_INICIO '01-04-2008', '19-07-2009'
GO


EXEC SP_LISTA_FECHA_INICIO
GO
