'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIENTE
    Public Property COD_CLI As String
    Public Property NOMBRES As String
    Public Property APE_PATER_CLI As String
    Public Property APE_MATER_CLI As String
    Public Property DIRECCION_CLI As String
    Public Property TELEFONO_CLI As String
    Public Property COD_DIST As String
    Public Property CORREO_E As String

    Public Overridable Property DISTRITO As DISTRITO

End Class
