'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DISTRITO
    Public Property COD_DIST As String
    Public Property DESCRIP_DIST As String

    Public Overridable Property CLIENTE As ICollection(Of CLIENTE) = New HashSet(Of CLIENTE)

End Class
