USE VENTAS2014
GO

IF OBJECT_ID('SP_LISTACLIENTES') IS NOT NULL
BEGIN
	DROP PROC SP_LISTACLIENTES
END
GO

CREATE PROC SP_LISTACLIENTES
AS
	SELECT [COD_CLI] as Codigo, CONCAT([NOMBRES],' ' ,[APE_PATER_CLI],' ' ,[APE_MATER_CLI]) as Nombre FROM CLIENTE
GO


IF OBJECT_ID('SP_LISTABOLETASXCLIENTE') IS NOT NULL
BEGIN
	DROP PROC SP_LISTABOLETASXCLIENTE
END
GO

CREATE PROC SP_LISTABOLETASXCLIENTE(@CODCLI char(6))
AS
	SELECT [COD_BOL] as codigo, [FECHA_BOL] as fecha, [ESTADO_BOL] as estao FROM BOLETA WHERE [COD_CLI]=@CODCLI
GO

IF OBJECT_ID('SP_LISTABOLETASDETALLE') IS NOT NULL
BEGIN
	DROP PROC SP_LISTABOLETASDETALLE
END
GO

CREATE PROC SP_LISTABOLETASDETALLE(@CODBOL char(6))
AS
	SELECT * FROM [dbo].[DETALLEBOLETA]  WHERE [COD_BOL]=@CODBOL
GO


