IF OBJECT_ID('SP_LISTAFECHA') IS NOT NULL
	DROP PROC SP_LISTAFECHA
GO

CREATE PROC SP_LISTAFECHA
AS
BEGIN
	SELECT [FECHA_BOL] FROM [dbo].[BOLETA] ORDER BY [FECHA_BOL] ASC
END
GO


IF OBJECT_ID('SP_BOLETASXFECHA') IS NOT NULL
	DROP PROC SP_BOLETASXFECHA
GO

CREATE PROC SP_BOLETASXFECHA
@FI SMALLDATETIME,
@FF SMALLDATETIME
AS
BEGIN
	SELECT * FROM [dbo].[BOLETA]
	WHERE [FECHA_BOL] BETWEEN  @FI AND @FF 
END
GO