'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTO
    Public Property COD_PRO As String
    Public Property DESCRIP_PRO As String
    Public Property PRECIO_PRO As Decimal
    Public Property STOCK_ACT_PRO As Integer
    Public Property STOCK_MIN_PRO As Integer

End Class
