IF OBJECT_ID('SP_LISTAEMPELADOS') IS NOT NULL
BEGIN
DROP PROC SP_LISTAEMPELADOS
END
GO
CREATE PROC SP_LISTAEMPELADOS
AS
SELECT [IdEmpleado],[ApeEmpleado],
[NomEmpleado],[FecNac],[DirEmpleado],
[idDistrito],[idCargo],[FecContrata]
FROM [RRHH].[empleados]
GO

--

IF OBJECT_ID('SP_LISTADISTRITOS') IS NOT NULL
BEGIN
DROP PROC SP_LISTADISTRITOS
END
GO
CREATE PROC SP_LISTADISTRITOS
AS
SELECT * FROM [RRHH].[Distritos]
GO

--


IF OBJECT_ID('SP_LISTACARGOS') IS NOT NULL
BEGIN
DROP PROC SP_LISTACARGOS
END
GO
CREATE PROC SP_LISTACARGOS
AS
SELECT * FROM [RRHH].[Cargos]
GO

--

IF OBJECT_ID('SP_ULTIMOEMPLEADO') IS NOT NULL
BEGIN
DROP PROC SP_ULTIMOEMPLEADO
END
GO
CREATE PROC SP_ULTIMOEMPLEADO
AS
SELECT TOP 1 [IdEmpleado] FROM [RRHH].[empleados]
ORDER BY [IdEmpleado] DESC
GO